# Milestone 1: Week 2 - Lasso, Ridge, Elastic Net Regression

In [47]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression, LassoCV, RidgeCV, ElasticNetCV
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, KFold, GridSearchCV
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import statsmodels.api as sm

import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

seed = 42

#### Lasso

In [5]:
socioeconomic_indicators = pd.read_csv(r'..\Processed Data\USDA Socioeconomic Indicators.csv')
socioeconomic_indicators.sample(5)

       FIPS_Code State  ... Unemployment_rate  Urban_Influence_Code
74991      55057    WI  ...          7.326370                   9.0
13552      16001    ID  ...          3.752986                   2.0
16446      17153    IL  ...          8.719533                   7.0
55769      42083    PA  ...          5.479326                   8.0
1491        1121    AL  ...          7.696519                   3.0

[5 rows x 13 columns]

Using Lasso to get coefficients for predicting `Median_Household_Income`

In [39]:
# Getting numeric columns for Lasso regression

X = socioeconomic_indicators.select_dtypes(include='number').drop(columns=['FIPS_Code', 'Median_Household_Income']) # while FIPS_Code is technically numeric, I am dropping it since it is more categorical for location
y = socioeconomic_indicators['Median_Household_Income']

feature_names = X.columns.tolist()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=seed)

# Testing different alpha scales
alphas = [0.001, 0.01, 0.1, 1, 10, 100, 1_000, 10_000]

lasso_cv = make_pipeline(StandardScaler(), LassoCV(alphas=alphas, cv=5, max_iter=100_000, random_state=seed))
lasso_cv.fit(X_train, y_train)

# Lasso model from pipeline
lasso_model = lasso_cv.named_steps['lassocv']

best_alpha = lasso_model.alpha_
print(f"Optimal Alpha: {best_alpha}\n")


print(f"Lasso coefficients with lambda = {best_alpha}:")
for name, coef in zip(feature_names, lasso_model.coef_):
    if abs(coef) > 1e-8:
        print(f"*** {name}: {coef: .6f}  <-- nonzero")
    else:
        print(f"    {name}: {coef: .6f}")

print("\nNumber of nonzero coefficients:", np.sum(np.abs(lasso_model.coef_) > 1e-8))


# Model evaluation
y_pred = lasso_cv.predict(X_test)
MAE = mean_absolute_error(y_test, y_pred)
RMSE = np.sqrt(mean_squared_error(y_test, y_pred))
R2 = r2_score(y_test, y_pred)


print("\nModel Evaluation")
print(f"*** Mean Absolute Error: ${MAE:,.2f}")
print(f"*** Root Mean Squared Error: ${RMSE:,.2f}")
print(f"*** R-squared Score: {R2:.4f}")

Optimal Alpha: 10.0

Lasso coefficients with lambda = 10.0:
*** Year: -161.068834  <-- nonzero
*** Civilian_labor_force:  61.692977  <-- nonzero
    Employed:  0.000000
*** Med_HH_Income_Percent_of_State_Total:  12836.351257  <-- nonzero
*** Metro:  34.284076  <-- nonzero
*** Rural_Urban_Continuum_Code: -1809.078529  <-- nonzero
*** Unemployed:  152.959898  <-- nonzero
*** Unemployment_rate: -1186.393508  <-- nonzero
*** Urban_Influence_Code:  111.347462  <-- nonzero

Number of nonzero coefficients: 8

Model Evaluation
*** Mean Absolute Error: $6,432.32
*** Root Mean Squared Error: $8,849.34
*** R-squared Score: 0.7117

Results:
  - Since `Employed` was dropped, it had high collinearity with other features. This is likely due to it being similar to `Civilian_labor_force`, which is the total `Employed` + total `Unemployed`.
  - `Med_HH_Income_Percent_of_State_Total` is the strongest positive driving force in this Lasso regression. This is likely because of data leakage since the median household income is used to calculate the percent of state total. I will rerun this Lasso regression with cross validation again with this feature dropped to get a clearer picture of the coefficients.

In [40]:
# Redoing LassoCV to prevent data leakage from Med_HH_Income_Percent_of_State_Total

X = socioeconomic_indicators.select_dtypes(include='number').drop(columns=['FIPS_Code', 'Median_Household_Income', 'Med_HH_Income_Percent_of_State_Total']) # while FIPS_Code is technically numeric, I am dropping it since it is more categorical for location
y = socioeconomic_indicators['Median_Household_Income']

feature_names = X.columns.tolist()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=seed)

# Testing different alpha scales
alphas = [0.001, 0.01, 0.1, 1, 10, 100, 1_000, 10_000]

lasso_cv = make_pipeline(StandardScaler(), LassoCV(alphas=alphas, cv=5, max_iter=100_000, random_state=seed))
lasso_cv.fit(X_train, y_train)

# Lasso model from pipeline
lasso_model = lasso_cv.named_steps['lassocv']

best_alpha = lasso_model.alpha_
print(f"Optimal Alpha: {best_alpha}\n")


print(f"Lasso coefficients with lambda = {best_alpha}:")
for name, coef in zip(feature_names, lasso_model.coef_):
    if abs(coef) > 1e-8:
        print(f"*** {name}: {coef: .6f}  <-- nonzero")
    else:
        print(f"    {name}: {coef: .6f}")

print("\nNumber of nonzero coefficients:", np.sum(np.abs(lasso_model.coef_) > 1e-8))


# Model evaluation
y_pred = lasso_cv.predict(X_test)
MAE = mean_absolute_error(y_test, y_pred)
RMSE = np.sqrt(mean_squared_error(y_test, y_pred))
R2 = r2_score(y_test, y_pred)


print("\nModel Evaluation")
print(f"*** Mean Absolute Error: ${MAE:,.2f}")
print(f"*** Root Mean Squared Error: ${RMSE:,.2f}")
print(f"*** R-squared Score: {R2:.4f}")

Optimal Alpha: 10.0

Lasso coefficients with lambda = 10.0:
*** Year: -771.357105  <-- nonzero
    Civilian_labor_force:  0.000000
    Employed:  0.000000
*** Metro:  1091.561966  <-- nonzero
*** Rural_Urban_Continuum_Code: -5536.854461  <-- nonzero
*** Unemployed:  384.328665  <-- nonzero
*** Unemployment_rate: -5886.147130  <-- nonzero
*** Urban_Influence_Code: -537.709256  <-- nonzero

Number of nonzero coefficients: 6

Model Evaluation
*** Mean Absolute Error: $10,342.01
*** Root Mean Squared Error: $13,868.24
*** R-squared Score: 0.2919

Results:
  - `Civilian_labor_force` and `Employed` were dropped. This makes sense because we already capture that information through keeping the `Unemployed` and `Unemployment_rate`. Having both the employed and unemployed features would be redundant because
  - The strongest negative impacted features in predicting the `Median_Household_Income` were `Unemployment_rate`, `Rural_Urban_Continuum_Code`, and `Year`.
    - The `Unemployment_rate` being the most negative coefficient makes sense for the domain of this dataset because when there are higher rates of unemployment, the `Median_Household_Income` would decrease as the workforce shrinks.
    - `Rural_Urban_Continuum_Code` being the second most negative feature shows that there is potentially a pattern with the size and location of counties negatively impacts `Median_Household_Income`. This makes sense because as the code increases, the smaller and more rural the county is. Smaller, rural counties typically have less job opportunities, therefore the household incomes likely are less than larger or more urban counties that have more job opportunities.
    - Interestingly, `Year` still has a relatively strong negative coefficient. This may mean that the baseline median incomes in this dataset trend slightly downward in the later years.
  - The strongest positive impacted features in predicting the `Median_Household_Income` were `Metro` and `Unemployed`
    - `Metro` makes sense because if the county is classified as a metropolitan area, there is likely more job opportunities and higher wages compared to rural or smaller counties. So, if a county is classified as a `Metro`, it will see a positive boost in the prediction formula.
    - `Unemployed`, the total number of people without work, is more interesting that it has a positive coefficient. My theory is that it has proportional to total population. Larger counties with higher income may have more unemployed but that is simply due to the size of the county rather than necessarily a higher `Unemployment_rate`.

Interpretation:

Overall, I do not have a problem with how the LassoCV model got rid of `Civilian_labor_force` and `Employed` in order to predict `Median_Household_Income`. This is because the features are redundant when we have the numbers for people who are `Unemployed` and the `Unemployment_rate`, which captures enough information about the economy to make predictions.

Comparison between the models:
  - Original model with potential data leakage had a lower MAE ($6,432.32 vs. $10,342.01)
  - Original model with potential data leakage had a lower RMSE ($8,849.34 vs. $13,868.24)
  - Original model with potential data leakage had a significantly higher R^2 Score (0.7117 vs. 0.2919)

This shows that while using `Med_HH_Income_Percent_of_State_Total` in the orginal LassoCV model resulted in more accurate predictions and explained a higher proportion of the variance in `Median_Household_Income`, the model essentially was cheating (leaking data) to more accurately predict the target. While R^2 of 0.2919 for the non-data-leaking model seems very low, for predicting household income the errors don't seem significantly higher compared to the model with the data leakage. According to [Duke University](https://people.duke.edu/~rnau/rsquared.htm),"if R-squared is very close to 1, and the data consists of time series, this is usually a bad sign rather than a good one." However when it comes to social science, which socioeconomics can be categorized, a low R-squared is not necessarily bad. A 25% R-squared may actually be considered quite meaningful. In order to further analyze the models, we would need to check for the statistical significance of each feature and consider whether the R-squared of 0.7117 in the original model is outside of the acceptable range for social science machine learning models.

#### Ridge

In [41]:
census = pd.read_csv('..\Processed Data\Census Demographics.csv')
census.head()

    GISJOIN    STATE  ...  pop_85_years_and_older_2010  pop_85_years_and_older_2020
0  G0100010  Alabama  ...                        551.0                        927.0
1  G0100030  Alabama  ...                       3233.0                       4606.0
2  G0100050  Alabama  ...                        443.0                        492.0
3  G0100070  Alabama  ...                        279.0                        353.0
4  G0100090  Alabama  ...                        808.0                       1053.0

[5 rows x 133 columns]

With Ridge Regression, it ensures that all coefficients have some weight unlike Lasso Regression. This is important when there may be collinearity but I don't want to choose between the two collinear features (either arbitrarily from the automatic decisions of the model's algorithm or by manually correcting for collinearity). 

Above is a good example with my data to show because a lot of the columns are population totals for certain age groups, sex, and year. Of course when adding these up you get the total population given that year so there will be high collinearity with multiple features in this dataset. Let's run Ridge Regression to apply some weight to all features rather than cancelling some out like what happened with Lasso Regression.

In [44]:
# For these models, let's take in all the historical data for each county in the U.S. to predict the total population of the most recent decade: 2020

X = census.select_dtypes(include="number").drop(columns=['total_pop_2020'])
y = census['total_pop_2020']

ridge_feature_names = X.columns.tolist()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=seed)

# Testing different alpha scales
alphas = [0.001, 0.01, 0.1, 1, 10, 100, 1_000, 10_000]

# Using KFold to have reproducibility with CV since RidgeCV has no random_state
cv_splitter = KFold(n_splits=5, shuffle=True, random_state=seed)

# Ridge is also sensitive to scale, so I need to standardize features first
ridge_cv = make_pipeline(StandardScaler(), RidgeCV(alphas=alphas, cv=cv_splitter, scoring='neg_mean_squared_error'))
ridge_cv.fit(X_train, y_train)

# Ridge model from pipeline
ridge_model = ridge_cv.named_steps['ridgecv']

best_ridge_alpha = ridge_model.alpha_
print(f"Optimal Alpha: {best_ridge_alpha}\n")

print(f"Ridge coefficients with lambda = {best_ridge_alpha}:")
for name, coef in zip(ridge_feature_names, ridge_model.coef_):
    if abs(coef) > 1e-8:
        print(f"*** {name}: {coef: .6f}")
    else:
        print(f"    {name}: {coef: .6f} <-- effectively zero")

print("\nNumber of nonzero coefficients:", np.sum(np.abs(ridge_model.coef_) > 1e-8))


# Model evaluation
y_pred_ridge = ridge_cv.predict(X_test)
MAE_ridge = mean_absolute_error(y_test, y_pred_ridge)
RMSE_ridge = np.sqrt(mean_squared_error(y_test, y_pred_ridge))
R2_ridge = r2_score(y_test, y_pred_ridge)


print("\nModel Evaluation")
print(f"*** Mean Absolute Error: {MAE_ridge:,.0f} people")
print(f"*** Root Mean Squared Error: {RMSE_ridge:,.0f} people")
print(f"*** R-squared Score: {R2_ridge:.4f}")

Optimal Alpha: 0.01

Ridge coefficients with lambda = 0.01:
*** STATEFP: -10.414082
*** STATENH: -10.414082
*** COUNTYFP:  16.328878
*** COUNTYNH:  16.328878
*** total_pop_1970:  28558.340947
*** total_pop_1980: -3990.558170
*** total_pop_1990:  2291.045832
*** total_pop_2000:  59253.743220
*** total_pop_2010:  204675.307444
*** male_pop_1970: -11768.362492
*** male_pop_1980:  10764.319338
*** male_pop_1990: -15835.358013
*** male_pop_2000:  29249.833084
*** male_pop_2010: -84070.574367
*** male_pop_2020:  124494.759786
*** female_pop_1970: -26222.950255
*** female_pop_1980:  31280.067808
*** female_pop_1990: -1896.034233
*** female_pop_2000:  44267.962466
*** female_pop_2010: -39869.581190
*** female_pop_2020:  45825.644966
*** pop_under_5_years_1970: -617.914155
*** pop_under_5_years_1980:  7321.296297
*** pop_under_5_years_1990: -2762.429311
*** pop_under_5_years_2000:  728.927897
*** pop_under_5_years_2010: -23518.427144
*** pop_under_5_years_2020:  16450.157825
*** pop_5_9_years_1970:  1244.123521
*** pop_5_9_years_1980: -13391.299441
*** pop_5_9_years_1990: -14792.581645
*** pop_5_9_years_2000: -26617.314928
*** pop_5_9_years_2010:  22495.396219
*** pop_5_9_years_2020:  2257.531968
*** pop_10_14_years_1970: -3855.052544
*** pop_10_14_years_1980:  5169.598284
*** pop_10_14_years_1990:  6098.267823
*** pop_10_14_years_2000: -6123.320918
*** pop_10_14_years_2010: -18999.704906
*** pop_10_14_years_2020:  50929.921900
*** pop_15_17_years_1970:  1426.934241
*** pop_15_17_years_1980: -5001.104829
*** pop_15_17_years_1990:  10326.871306
*** pop_15_17_years_2000: -8012.476695
*** pop_15_17_years_2010:  11099.500857
*** pop_15_17_years_2020: -44320.648688
*** pop_18_19_years_1970:  1756.300815
*** pop_18_19_years_1980:  304.008430
*** pop_18_19_years_1990: -4122.008925
*** pop_18_19_years_2000:  4677.958710
*** pop_18_19_years_2010:  3353.474244
*** pop_18_19_years_2020:  5974.952187
*** pop_20_years_1970: -1673.538691
*** pop_20_years_1980: -397.251358
*** pop_20_years_1990: -84.705706
*** pop_20_years_2000: -11586.171708
*** pop_20_years_2010: -7065.957869
*** pop_20_years_2020:  10757.823810
*** pop_21_years_1970: -756.898912
*** pop_21_years_1980: -2680.124664
*** pop_21_years_1990:  6133.333455
*** pop_21_years_2000: -3700.112184
*** pop_21_years_2010: -2341.878831
*** pop_21_years_2020: -5690.860777
*** pop_22_24_years_1970:  2317.370827
*** pop_22_24_years_1980:  2968.761118
*** pop_22_24_years_1990:  2057.190337
*** pop_22_24_years_2000: -922.618048
*** pop_22_24_years_2010:  5443.928210
*** pop_22_24_years_2020:  3915.499732
*** pop_25_29_years_1970: -1939.850436
*** pop_25_29_years_1980: -5380.877091
*** pop_25_29_years_1990: -5371.873506
*** pop_25_29_years_2000: -17821.498044
*** pop_25_29_years_2010:  4967.054616
*** pop_25_29_years_2020: -1297.635564
*** pop_30_34_years_1970:  2753.928035
*** pop_30_34_years_1980: -7699.628928
*** pop_30_34_years_1990:  16756.665907
*** pop_30_34_years_2000: -25126.789737
*** pop_30_34_years_2010: -5394.561859
*** pop_30_34_years_2020:  28825.307108
*** pop_35_44_years_1970:  7872.477845
*** pop_35_44_years_1980: -7333.896094
*** pop_35_44_years_1990: -267.044784
*** pop_35_44_years_2000:  18811.278742
*** pop_35_44_years_2010: -20574.191116
*** pop_35_44_years_2020: -6546.707129
*** pop_45_54_years_1970:  3757.139863
*** pop_45_54_years_1980: -8771.766772
*** pop_45_54_years_1990: -7738.434138
*** pop_45_54_years_2000: -10801.735705
*** pop_45_54_years_2010: -37215.874848
*** pop_45_54_years_2020:  57433.535146
*** pop_55_59_years_1970: -20421.705326
*** pop_55_59_years_1980:  9632.072861
*** pop_55_59_years_1990: -2885.439990
*** pop_55_59_years_2000: -62.779841
*** pop_55_59_years_2010: -12910.822861
*** pop_55_59_years_2020:  15148.364353
*** pop_60_61_years_1970:  6839.462882
*** pop_60_61_years_1980: -1412.232445
*** pop_60_61_years_1990: -971.992246
*** pop_60_61_years_2000: -1928.623283
*** pop_60_61_years_2010: -3927.281818
*** pop_60_61_years_2020:  9098.112251
*** pop_62_64_years_1970:  13367.731576
*** pop_62_64_years_1980: -2232.716954
*** pop_62_64_years_1990: -2985.589782
*** pop_62_64_years_2000: -12771.270064
*** pop_62_64_years_2010: -13905.877861
*** pop_62_64_years_2020: -21174.178372
*** pop_65_74_years_1970: -8943.839708
*** pop_65_74_years_1980: -878.382474
*** pop_65_74_years_1990:  4194.651182
*** pop_65_74_years_2000: -14346.071041
*** pop_65_74_years_2010:  37271.032739
*** pop_65_74_years_2020:  38650.986740
*** pop_75_84_years_1970:  12335.061124
*** pop_75_84_years_1980: -15555.891092
*** pop_75_84_years_1990:  3523.069022
*** pop_75_84_years_2000: -9720.210464
*** pop_75_84_years_2010: -833.116849
*** pop_75_84_years_2020: -27696.779191
*** pop_85_years_and_older_1970: -3695.292878
*** pop_85_years_and_older_1980:  439.855297
*** pop_85_years_and_older_1990:  4219.224519
*** pop_85_years_and_older_2000: -2877.711692
*** pop_85_years_and_older_2010: -1272.044399
*** pop_85_years_and_older_2020:  13379.306698

Number of nonzero coefficients: 129

Model Evaluation
*** Mean Absolute Error: 702 people
*** Root Mean Squared Error: 2,568 people
*** R-squared Score: 0.9999

Results:
  - Of course this model is extremely overfitting the data as it used every feature and has essentially 1 as an R-squared.

As an experiment, let's run the same model again but this time dropping all of the other _2020 features to still try to predict the total populations in 2020 for each county. This would use historical data in order to make predictions for the latest decade.

In [45]:
columns_to_drop = [col for col in census.columns if '2020' in col]

X = census.select_dtypes(include="number").drop(columns=columns_to_drop)
y = census['total_pop_2020']

ridge_feature_names = X.columns.tolist()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=seed)

# Testing different alpha scales
alphas = [0.001, 0.01, 0.1, 1, 10, 100, 1_000, 10_000]

# Using KFold to have reproducibility with CV since RidgeCV has no random_state
cv_splitter = KFold(n_splits=5, shuffle=True, random_state=seed)

# Ridge is also sensitive to scale, so I need to standardize features first
ridge_cv = make_pipeline(StandardScaler(), RidgeCV(alphas=alphas, cv=cv_splitter, scoring='neg_mean_squared_error'))
ridge_cv.fit(X_train, y_train)

# Ridge model from pipeline
ridge_model = ridge_cv.named_steps['ridgecv']

best_ridge_alpha = ridge_model.alpha_
print(f"Optimal Alpha: {best_ridge_alpha}\n")

print(f"Ridge coefficients with lambda = {best_ridge_alpha}:")
for name, coef in zip(ridge_feature_names, ridge_model.coef_):
    if abs(coef) > 1e-8:
        print(f"*** {name}: {coef: .6f}")
    else:
        print(f"    {name}: {coef: .6f} <-- effectively zero")

print("\nNumber of nonzero coefficients:", np.sum(np.abs(ridge_model.coef_) > 1e-8))


# Model evaluation
y_pred_ridge = ridge_cv.predict(X_test)
MAE_ridge = mean_absolute_error(y_test, y_pred_ridge)
RMSE_ridge = np.sqrt(mean_squared_error(y_test, y_pred_ridge))
R2_ridge = r2_score(y_test, y_pred_ridge)


print("\nModel Evaluation")
print(f"*** Mean Absolute Error: {MAE_ridge:,.0f} people")
print(f"*** Root Mean Squared Error: {RMSE_ridge:,.0f} people")
print(f"*** R-squared Score: {R2_ridge:.4f}")

Optimal Alpha: 0.1

Ridge coefficients with lambda = 0.1:
*** STATEFP:  236.951726
*** STATENH:  236.951726
*** COUNTYFP:  46.186122
*** COUNTYNH:  46.186122
*** total_pop_1970:  7514.684954
*** total_pop_1980: -19981.791740
*** total_pop_1990:  44521.590246
*** total_pop_2000:  145511.044088
*** total_pop_2010:  76547.648461
*** male_pop_1970: -68460.550866
*** male_pop_1980:  48390.291936
*** male_pop_1990: -11016.070074
*** male_pop_2000: -36837.914244
*** male_pop_2010:  39200.499085
*** female_pop_1970:  4136.738602
*** female_pop_1980:  76674.181003
*** female_pop_1990: -19231.622829
*** female_pop_2000:  34932.700651
*** female_pop_2010:  66245.701231
*** pop_under_5_years_1970:  40840.905159
*** pop_under_5_years_1980:  23315.977906
*** pop_under_5_years_1990: -23845.302528
*** pop_under_5_years_2000: -96459.317194
*** pop_under_5_years_2010:  59793.322054
*** pop_5_9_years_1970: -70448.005593
*** pop_5_9_years_1980: -34944.301505
*** pop_5_9_years_1990: -29713.397830
*** pop_5_9_years_2000: -1842.343877
*** pop_5_9_years_2010:  60529.655740
*** pop_10_14_years_1970:  35755.424307
*** pop_10_14_years_1980:  7094.403092
*** pop_10_14_years_1990: -28932.881787
*** pop_10_14_years_2000:  56961.503318
*** pop_10_14_years_2010:  21840.179983
*** pop_15_17_years_1970:  3113.673585
*** pop_15_17_years_1980:  12083.943958
*** pop_15_17_years_1990:  6784.840870
*** pop_15_17_years_2000:  25839.745661
*** pop_15_17_years_2010: -121568.767557
*** pop_18_19_years_1970:  2556.872225
*** pop_18_19_years_1980: -6856.921229
*** pop_18_19_years_1990:  7543.567834
*** pop_18_19_years_2000:  5771.022555
*** pop_18_19_years_2010: -19044.483794
*** pop_20_years_1970: -2497.521729
*** pop_20_years_1980: -8298.074595
*** pop_20_years_1990: -28783.930978
*** pop_20_years_2000: -977.217224
*** pop_20_years_2010:  29698.712544
*** pop_21_years_1970:  7798.176681
*** pop_21_years_1980: -3386.555370
*** pop_21_years_1990:  14691.442303
*** pop_21_years_2000: -2102.668637
*** pop_21_years_2010: -4660.980234
*** pop_22_24_years_1970:  18696.976175
*** pop_22_24_years_1980: -32446.360478
*** pop_22_24_years_1990:  48317.491296
*** pop_22_24_years_2000: -31215.322663
*** pop_22_24_years_2010:  486.466524
*** pop_25_29_years_1970:  42498.058580
*** pop_25_29_years_1980:  2737.263707
*** pop_25_29_years_1990: -55905.611697
*** pop_25_29_years_2000:  24751.631907
*** pop_25_29_years_2010:  45639.795637
*** pop_30_34_years_1970: -75710.571920
*** pop_30_34_years_1980: -63184.233471
*** pop_30_34_years_1990: -10623.202164
*** pop_30_34_years_2000: -62911.299134
*** pop_30_34_years_2010: -16419.591764
*** pop_35_44_years_1970:  53137.455711
*** pop_35_44_years_1980:  9446.292352
*** pop_35_44_years_1990:  37536.183483
*** pop_35_44_years_2000:  50674.656596
*** pop_35_44_years_2010:  95711.271311
*** pop_45_54_years_1970:  3188.352408
*** pop_45_54_years_1980:  30321.645165
*** pop_45_54_years_1990: -39512.127020
*** pop_45_54_years_2000:  42254.829548
*** pop_45_54_years_2010:  43506.817460
*** pop_55_59_years_1970: -39048.770196
*** pop_55_59_years_1980:  248.090638
*** pop_55_59_years_1990: -22954.524429
*** pop_55_59_years_2000: -53924.330885
*** pop_55_59_years_2010: -34582.589156
*** pop_60_61_years_1970: -131.616348
*** pop_60_61_years_1980: -26604.108501
*** pop_60_61_years_1990: -2381.816332
*** pop_60_61_years_2000:  1056.114334
*** pop_60_61_years_2010: -67883.191511
*** pop_62_64_years_1970:  27806.296839
*** pop_62_64_years_1980:  10016.179052
*** pop_62_64_years_1990: -2073.834543
*** pop_62_64_years_2000:  4430.529564
*** pop_62_64_years_2010:  24675.118455
*** pop_65_74_years_1970: -566.107709
*** pop_65_74_years_1980: -30596.151011
*** pop_65_74_years_1990:  35119.657682
*** pop_65_74_years_2000: -7742.033354
*** pop_65_74_years_2010:  86138.557911
*** pop_75_84_years_1970:  31964.503986
*** pop_75_84_years_1980: -76537.658444
*** pop_75_84_years_1990:  27541.821813
*** pop_75_84_years_2000: -15158.212337
*** pop_75_84_years_2010: -56126.136746
*** pop_85_years_and_older_1970: -1869.012534
*** pop_85_years_and_older_1980: -11631.000184
*** pop_85_years_and_older_1990:  38976.539459
*** pop_85_years_and_older_2000: -4880.304018
*** pop_85_years_and_older_2010:  7048.807945

Number of nonzero coefficients: 109

Model Evaluation
*** Mean Absolute Error: 4,321 people
*** Root Mean Squared Error: 11,073 people
*** R-squared Score: 0.9989

Results and Interpretation:

While the errors significantly increased, we see that the R-squared is still essentially 1. By dropping the _2020 features, we eliminated the massive data leak in predicting the `total_pop_2020`. Our errors are large so this shows that it can get relatively close for medium to largely populated counties which shows this model is definitely better in that regard instead of simply memorizing the data and having very low errors. However because R-squared wasn't reduced by much, I can conclude that it is able to explain the scale in counties but not the actual changes. The main issue with these models is that there is severe multicollinearity because the populations are captured multiple times. This results in an overly complex model with very small and large coefficients in order to predict `total_pop_2020`. If we were to use this model on new data, it would likely fail to generalize. 

In order to address the multicollinearity and overfitting, it might be better to create new features for the target. For example, we could engineer the historical growth rates into percentages and force the model to learn more of the patterns that drive growth rather than simply memorizing past population data. Another option is that we could convert the raw data itself into proportions of the total population for that decade while keeping the raw total population numbers. If feature engineering is not the best way, we could reign in the model itself. Given that the alpha 0.1 gave the best predictive score, we could force the alpha to be larger. The tradeoff is that the accuracy will be lower, but the coefficients could result in a more stable, generalized context to allow for new data later on. Finally, the last option is to use Elastic Net Regression which takes both Lasso and Ridge pentalties (L1 and L2 respectively). By finding a balance in the l1_ratio (proportion of Lasso to Ridge), Lasso will zero out features that offer less predictive value while Ridge stabilizes and groups correlated features together.

#### Elastic Net

In [ ]:
# Continuing with same dataset and target to show how Elastic Net could help with this situation

columns_to_drop = [col for col in census.columns if '2020' in col]

X = census.select_dtypes(include="number").drop(columns=columns_to_drop)
y = census['total_pop_2020']

EN_feature_names = X.columns.tolist()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=seed)

# Adjusted the alphas to be larger in order to avoid overfitting like what we found previously
alphas = [10, 100, 1_000, 10_000, 100_000]
l1_ratios = [0.1, 0.2, 0.3, 0.5]

# Using KFold to have reproducibility with CV since RidgeCV has no random_state
cv_splitter = KFold(n_splits=5, shuffle=True, random_state=seed)

# Ridge and Lasso are both sensitive to scale, so I need to standardize features first
EN_cv = make_pipeline(StandardScaler(), ElasticNetCV(l1_ratio=l1_ratios, alphas=alphas, cv=cv_splitter, max_iter=100_000, n_jobs=-1))
EN_cv.fit(X_train, y_train)

# Elastic Net model from pipeline
EN_model = EN_cv.named_steps['elasticnetcv']

best_EN_alpha = EN_model.alpha_
best_EN_l1 = EN_model.l1_ratio_
print(f"Optimal Alpha: {best_EN_alpha}\n")
print(f"Optimal L1 Ratio: {best_EN_l1}\n")

print(f"Ridge coefficients with lambda = {best_EN_alpha}:")
for name, coef in zip(EN_feature_names, EN_model.coef_):
    if abs(coef) > 1e-8:
        print(f"*** {name}: {coef: .6f}")
    else:
        print(f"    {name}: {coef: .6f} <-- zeroed out")

print("\nNumber of nonzero coefficients:", np.sum(np.abs(EN_model.coef_) > 1e-8))


# Model evaluation
y_pred_EN = EN_cv.predict(X_test)
MAE_EN = mean_absolute_error(y_test, y_pred_EN)
RMSE_EN = np.sqrt(mean_squared_error(y_test, y_pred_EN))
R2_EN = r2_score(y_test, y_pred_EN)


print("\nModel Evaluation")
print(f"*** Mean Absolute Error: {MAE_EN:,.0f} people")
print(f"*** Root Mean Squared Error: {RMSE_EN:,.0f} people")
print(f"*** R-squared Score: {R2_EN:.4f}")

Optimal Alpha: 10

Optimal L1 Ratio: 0.7

Ridge coefficients with lambda = 10:
*** STATEFP: -347.329765
*** STATENH: -347.330679
*** COUNTYFP: -89.868308
*** COUNTYNH: -89.868026
*** total_pop_1970:  313.960701
*** total_pop_1980:  1549.889271
*** total_pop_1990:  2921.891023
*** total_pop_2000:  5280.412891
*** total_pop_2010:  6506.422402
*** male_pop_1970:  425.383925
*** male_pop_1980:  1660.230587
*** male_pop_1990:  3011.454054
*** male_pop_2000:  5276.686244
*** male_pop_2010:  6324.167145
*** female_pop_1970:  270.223366
*** female_pop_1980:  1395.856747
*** female_pop_1990:  2795.924950
*** female_pop_2000:  4942.362111
*** female_pop_2010:  6152.869165
*** pop_under_5_years_1970:  603.067852
*** pop_under_5_years_1980:  1854.288452
*** pop_under_5_years_1990:  3117.914031
*** pop_under_5_years_2000:  5460.530330
*** pop_under_5_years_2010:  7188.733200
*** pop_5_9_years_1970:  686.961708
*** pop_5_9_years_1980:  1767.845870
*** pop_5_9_years_1990:  3266.146295
*** pop_5_9_years_2000:  5090.197817
*** pop_5_9_years_2010:  7240.878847
*** pop_10_14_years_1970:  520.837879
*** pop_10_14_years_1980:  1629.449122
*** pop_10_14_years_1990:  3030.646482
*** pop_10_14_years_2000:  5145.431796
*** pop_10_14_years_2010:  6690.088440
*** pop_15_17_years_1970:  404.547422
*** pop_15_17_years_1980:  1435.381742
*** pop_15_17_years_1990:  2661.808561
*** pop_15_17_years_2000:  5025.608629
*** pop_15_17_years_2010:  6066.639797
*** pop_18_19_years_1970:  543.917142
*** pop_18_19_years_1980:  1769.953471
*** pop_18_19_years_1990:  2662.711437
*** pop_18_19_years_2000:  4781.675605
*** pop_18_19_years_2010:  5494.119654
*** pop_20_years_1970:  762.991693
*** pop_20_years_1980:  1788.585993
*** pop_20_years_1990:  2729.446083
*** pop_20_years_2000:  4589.098283
*** pop_20_years_2010:  5293.869912
*** pop_21_years_1970:  845.753138
*** pop_21_years_1980:  1745.715004
*** pop_21_years_1990:  2685.717595
*** pop_21_years_2000:  4279.294660
*** pop_21_years_2010:  5125.024113
*** pop_22_24_years_1970:  766.182750
*** pop_22_24_years_1980:  1828.763359
*** pop_22_24_years_1990:  2815.597662
*** pop_22_24_years_2000:  4741.866153
*** pop_22_24_years_2010:  5587.367205
*** pop_25_29_years_1970:  843.450921
*** pop_25_29_years_1980:  1942.610856
*** pop_25_29_years_1990:  3302.338519
*** pop_25_29_years_2000:  4828.589261
*** pop_25_29_years_2010:  5730.529492
*** pop_30_34_years_1970:  844.088295
*** pop_30_34_years_1980:  2189.849935
*** pop_30_34_years_1990:  3377.591580
*** pop_30_34_years_2000:  4689.563006
*** pop_30_34_years_2010:  6086.177769
*** pop_35_44_years_1970:  392.421742
*** pop_35_44_years_1980:  1931.034218
*** pop_35_44_years_1990:  3375.087938
*** pop_35_44_years_2000:  5078.550761
*** pop_35_44_years_2010:  6064.151859
*** pop_45_54_years_1970: -66.621413
*** pop_45_54_years_1980:  1110.968211
*** pop_45_54_years_1990:  2972.603453
*** pop_45_54_years_2000:  4655.249546
*** pop_45_54_years_2010:  5781.619498
*** pop_55_59_years_1970: -301.222629
*** pop_55_59_years_1980:  907.742328
*** pop_55_59_years_1990:  2471.262305
*** pop_55_59_years_2000:  4616.641033
*** pop_55_59_years_2010:  5527.294889
*** pop_60_61_years_1970: -257.609269
*** pop_60_61_years_1980:  936.915360
*** pop_60_61_years_1990:  2227.747393
*** pop_60_61_years_2000:  4585.277979
*** pop_60_61_years_2010:  5654.314070
*** pop_62_64_years_1970: -256.259378
*** pop_62_64_years_1980:  992.653084
*** pop_62_64_years_1990:  2272.380499
*** pop_62_64_years_2000:  4457.400248
*** pop_62_64_years_2010:  5862.481905
*** pop_65_74_years_1970: -332.252923
*** pop_65_74_years_1980:  1059.118257
*** pop_65_74_years_1990:  2578.313404
*** pop_65_74_years_2000:  4372.396000
*** pop_65_74_years_2010:  5984.348392
*** pop_75_84_years_1970: -495.508059
*** pop_75_84_years_1980:  456.729519
*** pop_75_84_years_1990:  2206.814424
*** pop_75_84_years_2000:  4188.871081
*** pop_75_84_years_2010:  4911.286513
*** pop_85_years_and_older_1970: -289.164332
*** pop_85_years_and_older_1980:  290.821935
*** pop_85_years_and_older_1990:  1523.134812
*** pop_85_years_and_older_2000:  3598.435713
*** pop_85_years_and_older_2010:  4220.493496

Number of nonzero coefficients: 109

Model Evaluation
*** Mean Absolute Error: 18,430 people
*** Root Mean Squared Error: 59,294 people
*** R-squared Score: 0.9680

Results and Interpretations:
  - Even after playing around with the ranges for alpha and l1_ratio, we are still capturing almost all of the variance. The tradeoff I found when messing with the hyperparameter ranges is that if you increase alpha and decrease l1_ratio they both lead to a lower R-squared but significantly higher errors. This also shows that there needs to be either more precise feature selection first before building the final model or to do feature engineering in order to have more precise predictions while generalizing. To show this, I will do some feature engineering in attempt to create a more generalized model while having more acceptable errors (finding the balance in errors for small, medium, and large populations).

In [52]:
census_engineered = census.copy()

# New target: growth rate from 2010 to 2020
census_engineered['recent_growth_rate'] = (census_engineered['total_pop_2020'] - census_engineered['total_pop_2010']) / census_engineered['total_pop_2010']

# converting 2010 features into proportions
cols_2010 = [col for col in census_engineered.columns if '2010' in col and col != 'total_pop_2010']

for col in cols_2010:
    new_col_name = col.replace('pop_', 'pct_')
    census_engineered[new_col_name] = census_engineered[col] / census_engineered['total_pop_2010']

# dropping features that would leak information
cols_to_drop = [col for col in census_engineered.columns if '2020' in col or '19' in col or '2000' in col or col == 'total_pop_2010']
cols_to_drop.extend(cols_2010)

census_engineered = census_engineered.drop(columns=cols_to_drop)
census_engineered.head()

    GISJOIN    STATE  ...  pct_75_84_years_2010  pct_85_years_and_older_2010
0  G0100010  Alabama  ...              0.036320                     0.010097
1  G0100030  Alabama  ...              0.052297                     0.017738
2  G0100050  Alabama  ...              0.044724                     0.016134
3  G0100070  Alabama  ...              0.039450                     0.012175
4  G0100090  Alabama  ...              0.044520                     0.014096

[5 rows x 27 columns]

In [59]:
X_engineered = census_engineered.select_dtypes(include="number").drop(columns=['recent_growth_rate'])
y_engineered = census_engineered['recent_growth_rate']

EN_feature_names = X_engineered.columns.tolist()

X_train, X_test, y_train, y_test = train_test_split(X_engineered, y_engineered, test_size=0.2, random_state=seed)

alphas = [0.00001, 0.0001, 0.001, 0.01, 1]
# l1_ratios = [0.01, 0.05, 0.1, 0.25, 0.4]
l1_ratios = [0.01, 0.05, 0.1, 0.25, 0.4, 0.5, 0.75, 0.9]


# Using KFold to have reproducibility with CV since RidgeCV has no random_state
cv_splitter = KFold(n_splits=5, shuffle=True, random_state=seed)

# Ridge and Lasso are both sensitive to scale, so I need to standardize features first
EN_cv = make_pipeline(StandardScaler(), ElasticNetCV(l1_ratio=l1_ratios, alphas=alphas, cv=cv_splitter, max_iter=100_000, n_jobs=-1))
EN_cv.fit(X_train, y_train)

# Elastic Net model from pipeline
EN_model = EN_cv.named_steps['elasticnetcv']

best_EN_alpha = EN_model.alpha_
best_EN_l1 = EN_model.l1_ratio_
print(f"Optimal Alpha: {best_EN_alpha}\n")
print(f"Optimal L1 Ratio: {best_EN_l1}\n")

print(f"Ridge coefficients with lambda = {best_EN_alpha}:")
for name, coef in zip(EN_feature_names, EN_model.coef_):
    if abs(coef) > 1e-8:
        print(f"*** {name}: {coef: .6f} <-- nonzero")
    else:
        print(f"    {name}: {coef: .6f}")

print("\nNumber of nonzero coefficients:", np.sum(np.abs(EN_model.coef_) > 1e-8))


# Model evaluation
y_pred_EN = EN_cv.predict(X_test)
MAE_EN = mean_absolute_error(y_test, y_pred_EN)
RMSE_EN = np.sqrt(mean_squared_error(y_test, y_pred_EN))
R2_EN = r2_score(y_test, y_pred_EN)


print("\nModel Evaluation")
print(f"*** Mean Absolute Error: {MAE_EN * 100:.2f}%")
print(f"*** Root Mean Squared Error: {RMSE_EN * 100:.2f}%")
print(f"*** R-squared Score: {R2_EN:.4f}")

Optimal Alpha: 0.01

Optimal L1 Ratio: 0.5

Ridge coefficients with lambda = 0.01:
    STATEFP: -0.000000
    STATENH: -0.000000
*** COUNTYFP: -0.001586 <-- nonzero
*** COUNTYNH: -0.000721 <-- nonzero
*** male_pct_2010: -0.001558 <-- nonzero
*** female_pct_2010: -0.029236 <-- nonzero
*** pct_under_5_years_2010:  0.129714 <-- nonzero
    pct_5_9_years_2010: -0.000000
    pct_10_14_years_2010:  0.000000
    pct_15_17_years_2010: -0.000000
*** pct_20_years_2010:  0.002834 <-- nonzero
*** pct_21_years_2010:  0.048720 <-- nonzero
    pct_22_24_years_2010: -0.000000
*** pct_25_29_years_2010: -0.062366 <-- nonzero
*** pct_30_34_years_2010: -0.004241 <-- nonzero
*** pct_35_44_years_2010:  0.036699 <-- nonzero
*** pct_45_54_years_2010:  0.007256 <-- nonzero
    pct_55_59_years_2010: -0.000000
    pct_60_61_years_2010: -0.000000
*** pct_62_64_years_2010:  0.031681 <-- nonzero
    pct_65_74_years_2010:  0.000000
    pct_75_84_years_2010:  0.000000
    pct_85_years_and_older_2010: -0.000000

Number of nonzero coefficients: 12

Model Evaluation
*** Mean Absolute Error: 7.80%
*** Root Mean Squared Error: 13.23%
*** R-squared Score: 0.5422

Results:
  - After reducing the alphas and l1_ratios I was able to create a more generalized model in predicting the growth rates of the total population from 2010 to 2020. We have a lower R-squared of 0.5328, which is an improvement from the near perfect R-squared scores from the previous models.
  - `pct_under_5_years_2010`, `pct_21_years_2010`, and `pct_35_44_years_2010` had the strongest positive coefficients.
    - This could mean that the proportion of young children, young adults, and people in their 30s-40s represent strong predictors because of they could be core age groups for county growth in the U.S. This could potentially represent parents and young children in growing populations as well as university and entry-level working-age people going to counties with opportunities. `pct_62_64_years_2010` is also another strong predictor as people nearing retirement age may move around to certain areas to retire. Besides thinking about people moving around, it makes sense that young families make up the strongest positive coefficients in predicting population growth as they are the age group having children which directly affects the population growth rate. The ages in between 22 and 34 is interesting as they are somewhat strong negative coefficients. This could be because this age group moves around more so it affects the county populations in the negative direction. 

Interpretation:

Overall, this model definitely generalizes better rather than overfitting because of the lower R-squared, elimination of some features, and the low but significant error rates. The balancing act was finding the right alpha and l1_ratio ranges. When alpha is low, it means the model is less restricted from penalization so it memorizes more of the training data. In contrast, when it is high there is more penalty for using features which results in underfitting. Now, the model has a more realistic R-squared score. In the previous models with near-perfect R-squared scores, they were artificially inflated by the raw population counts which resulted in capturing the variance in scale across U.S. counties (small counties remain small and large counties remain large). This combined with my feature engineering resulted in a more generalized model that provides valuable insights without simply memorizing the data with overly complicated coefficients.